# Generated by Django 2.0.8 on 2019-09-28 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emails.EmailObject')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emails.EmailUser')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to='emails.EmailUser')),
            ],
        ),
    ]
