# Generated by Django 2.0.8 on 2019-09-28 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailuser',
            old_name='email',
            new_name='email_address',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='sender',
        ),
        migrations.AddField(
            model_name='emailobject',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='author', to='emails.EmailUser'),
            preserve_default=False,
        ),
    ]
